<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>ThabeSoft.DomainDrivenDesign</RootNamespace>
	</PropertyGroup>

	<PropertyGroup>

		<!--包信息-->
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<!--基础-->
		<Version>0.1.0-alpha.1</Version>
		<PackageId>ThabeSoft.DomainDrivenDesign.EntityFrameworkCore</PackageId>
		<Title>ThabeSoft.DomainDrivenDesign.EntityFrameworkCore</Title>

		<!--描述-->
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Description>领域驱动一些默认实现：聚合根、实体、等基类</Description>
		<PackageTags>DDD;DomainDrivenDesign;领域驱动设计;AggregateRoot;DomainEvent;ValueObject</PackageTags>

	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ThabeSoft.DomainDrivenDesign.Abstractions\ThabeSoft.DomainDrivenDesign.Abstractions.csproj" />
	</ItemGroup>

</Project>
