<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>ThabeSoft.DomainDrivenDesign.Infrastructure</RootNamespace>
	</PropertyGroup>

	<PropertyGroup>

		<!--包信息-->
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Version>0.1.0</Version>
		<PackageId>ThabeSoft.DomainDrivenDesign.EntityFrameworkCore</PackageId>
		<Title>ThabeSoft.DomainDrivenDesign.EntityFrameworkCore</Title>
		<Description>领域实体持久化Efcore实现</Description>

		<!--介绍-->
		<Authors>DaThabe</Authors>
		<Company>ThabeSoft</Company>
		<Product>DomainDrivenDesign..EntityFrameworkCore</Product>

		<!--仓库-->
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/thabesoft/DomainDrivenDesign</RepositoryUrl>
		<PackageProjectUrl>https://github.com/thabesoft/DomainDrivenDesign</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
	</ItemGroup>


	<ItemGroup>
	  <ProjectReference Include="..\ThabeSoft.DomainDrivenDesign.Abstractions\ThabeSoft.DomainDrivenDesign.Abstractions.csproj" />
	</ItemGroup>

</Project>
