<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>ThabeSoft.DomainDrivenDesign</RootNamespace>
	</PropertyGroup>

	<PropertyGroup>

		<!--包信息-->
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Version>0.1.0</Version>
		<PackageId>ThabeSoft.DomainDrivenDesign.Mediator</PackageId>
		<Title>ThabeSoft.DomainDrivenDesign.Mediator</Title>
		<Description>领域事件中介者分发器</Description>

		<!--介绍-->
		<Authors>DaThabe</Authors>
		<Company>ThabeSoft</Company>
		<Product>DomainDrivenDesign.Mediator</Product>

		<!--仓库-->
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/thabesoft/DomainDrivenDesign</RepositoryUrl>
		<PackageProjectUrl>https://github.com/thabesoft/DomainDrivenDesign</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>

	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
	  <PackageReference Include="ThabeSoft.Mediator.Abstractions" Version="1.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ThabeSoft.DomainDrivenDesign.Abstractions\ThabeSoft.DomainDrivenDesign.Abstractions.csproj" />
	</ItemGroup>

</Project>
