<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>ThabeSoft.DomainDrivenDesign</RootNamespace>
	</PropertyGroup>

	<!--包信息-->
	<PropertyGroup>

		<!--生成-->
		<GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<!--基础-->
		<Version>0.1.0-alpha.$([System.DateTime]::Now.ToString("yyMMdd-HHmmss"))</Version>
		<Title>ThabeSoft.DomainDrivenDesign.Mediator</Title>

		<!--描述-->
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Description>领域事件中介者分发器</Description>
		<PackageTags>DDD;DomainDrivenDesign;领域驱动设计;Mediator;中介者</PackageTags>
		<PackageIcon>nuget_icon.jpg</PackageIcon>

	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
	  <PackageReference Include="ThabeSoft.Mediator" Version="0.1.0-alpha.2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ThabeSoft.DomainDrivenDesign.Abstractions\ThabeSoft.DomainDrivenDesign.Abstractions.csproj" />
	</ItemGroup>

</Project>
