<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>preview</LangVersion>
	</PropertyGroup>

	<!--包信息-->
	<PropertyGroup>

		<!--生成-->
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<!--基础-->
		<PackageId>ThabeSoft.DomainDrivenDesign</PackageId>
		<Version>0.1.0-alpha.1</Version>
		<Title>ThabeSoft.DomainDrivenDesign</Title>

		<!--描述-->
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Description>领域驱动一些默认实现：聚合根、实体、等基类</Description>
		<PackageTags>DDD;DomainDrivenDesign;领域驱动设计;AggregateRoot;DomainEvent;ValueObject</PackageTags>

	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ThabeSoft.DomainDrivenDesign.Abstractions\ThabeSoft.DomainDrivenDesign.Abstractions.csproj" />
	</ItemGroup>

</Project>
