<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>preview</LangVersion>
	</PropertyGroup>

	<PropertyGroup>

		<!--包信息-->
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Version>0.1.1</Version>
		<PackageId>ThabeSoft.DomainDrivenDesign</PackageId>
		<Title>ThabeSoft.Ddd.Abstractions</Title>

		<!--介绍-->
		<Authors>DaThabe</Authors>
		<Company>ThabeSoft</Company>
		<Product>DomainDrivenDesign</Product>

		<!--仓库-->
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/thabesoft/DomainDrivenDesign</RepositoryUrl>
		<PackageProjectUrl>https://github.com/thabesoft/DomainDrivenDesign</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>

	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="ThabeSoft.Mediator" Version="0.1.3" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ThabeSoft.DomainDrivenDesign.Abstractions\ThabeSoft.DomainDrivenDesign.Abstractions.csproj" />
	  <ProjectReference Include="..\ThabeSoft.DomainDrivenDesign.Mediator\ThabeSoft.DomainDrivenDesign.Mediator.csproj" />
	  <ProjectReference Include="..\ThabeSoft.DomainDrivenDesign.EntityFrameworkCore\ThabeSoft.DomainDrivenDesign.EntityFrameworkCore.csproj" />
	</ItemGroup>

</Project>
